[package]
name = "crabby-ml"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = "^0.35.4"
serde = "1.0.193"
serde_json = "1.0.108"
derive_builder = "0.13.0"
